version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/hdl_registers"
    schedule:
      interval: "daily"
    labels:
      - Dependencies
    reviewers:
      - LukasVik

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - Dependencies
    reviewers:
      - LukasVik
